name: build-and-deploy
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel.
jobs:
build:
  runs-on: ubuntu-latest

  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your
    # job can access it
    - uses: actions/checkout@v2
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
          
    - name: Install nbconvert
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert notebook
      run: jupyter nbconvert --to python test.ipynb

    - name: Upload python script
      uses: actions/upload-artifact@v2
      with:
        name: test.py
        path: test.py